name: Ansible - Initial Setup

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Set up SSH
      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Ansible
      - name: "Install Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r ansible/requirements.yml

      - name: Create inventory
        run: |
          echo "${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USER }}" >> ~/inventory.ini

      - name: Setup Vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_pass

      - name: Run Playbook
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_BECOME_PASS }}
        run: |
          ansible-playbook -i ~/inventory.ini \
            playbooks/initial-setup.yml \
            --vault-password-file ~/.vault_pass